Auto-Update: true
Use-Vault: false
debug-mode: false
OPs-have-all: false
Use-UUID: true
Template:
  format: '<[time] [world] [prefix][name][suffix]> '
  time: '[h:mm aa]'
  multiPrefix: false
  multiPrefixSeparator: '&r, '
  multiSuffix: false
  multiSuffixSeparator: '&r-'
Worlds:
  world:
    nickname: '&e[World]&f'
Group:
  example:
    prefix: '&a[Example]&f'
    suffix: ''
    tier: 'exampleTier'
User:
  069a79f4-44e9-4726-a5be-fca90e38aaf5:
    prefix: '&c[Notch]&f'
    suffix: ''